services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./secrets/mysql.env
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    ports:
      - "8000:80"
    volumes:
      - ./secrets:/run/secrets
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge