services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=UI0iNQ67esJEGO3yuIA5lnuBBIL3fVKlillnszdW/0s=
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    privileged: true
    command: server -dev
    volumes:
      - ./vault-data:/vault/file
    networks:
      - vault

networks:
  vault:
    external: true