{{ with secret "kv/mysql" }}
MYSQL_USER={{ .Data.MYSQL_USER }}
MYSQL_PASSWORD={{ .Data.MYSQL_PASSWORD }}
MYSQL_ROOT_PASSWORD={{ .Data.MYSQL_ROOT_PASSWORD }}
MYSQL_DATABASE={{ .Data.MYSQL_DATABASE }}
{{ end }}